# Cucumber Configuration
cucumber.publish.enabled=false
cucumber.plugin=pretty,html:target/cucumber-reports,json:target/cucumber-reports/Cucumber.json,junit:target/cucumber-reports/Cucumber.xml,com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:

# Glue packages
cucumber.glue=auto.framework.selenium.cucumber.steps,auto.framework.selenium.cucumber.hooks

# Features location
cucumber.features=src/test/resources/features

# Options
cucumber.execution.dry-run=false
cucumber.execution.strict=true